### ISSUE TITLE
JavaScript in the project

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#103]
**Describe the bug**
When I look at the repository I find .js files under `www/`.

**To Reproduce**
1. Go to 'https://github.com/LuleaUniversityOfTechnology/2018-project-roaster'
2. Click on 'Languages statistics toolbar'
3. See 'JavaScript'

**Expected behavior**
No Javascript.

**Screenshots**
![2018-11-28-143219_993x70_scrot](https://user-images.githubusercontent.com/4541181/49155112-6bea0c00-f31a-11e8-91a7-e3a30634ebd7.png)

**Desktop (please complete the following information):**
 - OS: Linux voltaire 4.14.65-gentoo #10 SMP Mon Oct 22 19:18:56 CEST 2018 x86_64 Intel(R) Core(TM) i5-3427U
CPU @ 1.80GHz GenuineIntel GNU/Linux
 - Browser: Firefox
 - Version: 60.3.0

**Additional context**
I cannot sleep.

**Comment by JonasHedEng** [comment]
This is outrageous. Please resolve this immediately.

**Comment by willeponken** [comment]
Yes! This issue hasn't been resolved in 8 (!!!) days, what are you doing @Hjortsberg?!

**Comment by Hjortsberg** [comment]
![Alt Text](https://media.giphy.com/media/xT9DPr4VjeCgeiLoMo/giphy.gif)

**Comment by willeponken** [comment]
THIS IS BEAUTIFUL! :sob: :smile: 
![2018-12-06-213645_1001x65_scrot](https://user-images.githubusercontent.com/4541181/49610517-1909f780-f99f-11e8-88f7-e382323ad4c5.png)

**Comment by Hjortsberg** [comment]
(fixed: #124)
