### ISSUE TITLE
Add avatar support for users (requires new API endpoints)

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#111]
We should probably support avatars. I vote for just saving it as blobs in the PostgreSQL database.

**Comment by Hjortsberg** [comment]
I agree, blobs in dB will work!

**Comment by willeponken** [comment]
Okay great! We will probably allow JPEG and PNG. And compress (lossy) to a reasonable size for a blob store.

**Comment by willeponken** [comment]
Blocked by #55
