### ISSUE TITLE
User feed with latest updates from friends and themselves (requires new API endpoints)

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#112]
This is a requirement that we are required to implement to pass the course.

**Comment by willeponken** [comment]
@Hjortsberg I kinda got a panic when I remembered this... Discuss this sometime soon?

**Comment by Hjortsberg** [comment]
Heh, heeeeh. Yeah we kinda need to. One delimitation could be to not use websockets and just get new data when refreshed. And to use the pre-defined feeds in semantic UI.

**Comment by willeponken** [comment]
Yes, let's go with regular HTTP and pagination. Good enought, we don't really need any live feed.

**Comment by willeponken** [comment]
Blocked by #55
