### ISSUE TITLE
deployment is borken!

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#125]
Deploy script doesn't run even though a new PR is merged into master.

**Comment by willeponken** [comment]
It's not only the deploy scripts, Travis CI won't run the `master` branch build for some reason.

**Comment by willeponken** [comment]
I checked the Travis CI logs, it seems like GitHub isn't sending the `push` event to them anymore.

**Comment by Hjortsberg** [comment]
![PANIC](https://media.giphy.com/media/KmTnUKop0AfFm/giphy.gif)

**Comment by willeponken** [comment]
Yep, GitHub has problems:
https://www.traviscistatus.com/
https://status.github.com/messages

**Comment by willeponken** [comment]
According to them it should be fixed now, so... :thinking:

**Comment by Hjortsberg** [comment]
Soo, eh just a small PR to test?

**Comment by willeponken** [comment]
Woops missclick

**Comment by willeponken** [comment]
@Hjortsberg let's just wait an hour, I'm unable to trigger a rebuild through Travis CI, so maybe they still have some problems?

**Comment by Hjortsberg** [comment]
Yes, I have prepared the documentation PR so it's ready to merge whenever you say go.

**Comment by willeponken** [comment]
GO

**Comment by willeponken** [comment]
I HAVE BEEN WAITING, DIDN'T KNOW YOU WAITED FOR ME

**Comment by Hjortsberg** [comment]
haha I'll merge this as soon as i complete the open-heart surgery on my laptop.

**Comment by Hjortsberg** [comment]
Deployment is now fixed! Thank you GitHub!
