### ISSUE TITLE
Set up Cloud Front AWS

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#14]
Set up Cloud Front CDN before Elastic Load Balancer.

**Comment by willeponken** [comment]
Wasn't a bucket automatically set up when creating the application/EC2
instance?

Den tor 8 nov. 2018 20:28Philip Hjortsberg <notifications@github.com> skrev:

**Comment by willeponken** [comment]
As discussed in #18 we do not need any CDN right now, closing.
