### ISSUE TITLE
Nameservers doesn't seem to be configured

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#15]
Hello, it seems like _no_ nameservers are configured for roast.software:
![2018-11-08-164107_540x302_scrot](https://user-images.githubusercontent.com/4541181/48209360-37b3a900-e375-11e8-8379-783da77d392e.png)

The Namecheap NS' should at least appear, maybe something's wrong? @Hjortsberg

**Comment by Hjortsberg** [comment]
Found that i accidentally had the name servers for the faulty domain (roaster) in the config. Have changed these, now we wait until the changes propagate and see if it was enough.

**Comment by Hjortsberg** [comment]
![roast](https://user-images.githubusercontent.com/17297258/48216573-59b52780-e385-11e8-94ef-7502b3579eb3.PNG)

Seems to be resolving soon!

**Comment by willeponken** [comment]
Solved!
