### ISSUE TITLE
Design the web server architecture

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#16]
Design the web server architecture, such as where to define routes, models, and views. The file structure for this code base should be included.

Related to #13 and blocks #10.

**Comment by willeponken** [comment]
I personally enjoy using this file structure:
```
.
├── cmd/
│   └── roasterd/
├── controller/
├── doc/
├── middleware/
├── model/
├── static/
├── tool/
└── view/
```
Where:

    /cmd - main entry points for each binary
    /controller - routes according to MVC pattern
    /doc - documentation
    /middleware - interceptors for routes
    /model - interact with database according to MVC pattern
    /static - content that is served by the web server
    /tool - developer utilities
    /view - HTML views that are rendered for each web page

But this structure is made for static web pages. I'm unsure where to have the frontend code. Maybe it could be compiled and then put into the `/static` folder. In that case, either all development could occur in that folder, or we could add a submodule that points to a frontend repository.

I believe that this structure should probably be changed somewhat, but atleast it could be a start.

**Comment by Hjortsberg** [comment]
Feels like a stable foundation. Let us start here.

**Comment by willeponken** [comment]
Here's a revision of the prior structure! We will use the following:
```
.
├── cmd/
│   └── roasterd/
├── controller/
├── doc/
├── middleware/
├── model/
├── www/
└── tool/
```
Where:
```
    /cmd        - main entry points for each binary
    /controller - routes according to MVC pattern
    /doc        - documentation
    /middleware - interceptors for routes
    /model      - interact with database according to MVC pattern
    /www        - content that is served by the web server, such as HTML, CSS and JavaScript
    /tool       - developer utilities
```
