### ISSUE TITLE
Friends and user feed buttons are shown even if not logged in

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#161]
Woops, I'll fix, in like... 5 hours? Gotta walk the dog and buy some stuff first.

**Comment by Hjortsberg** [comment]
The legend says he never returned from that walk.

**Comment by willeponken** [comment]
Hehehe, It's actually fixed in #162, but not merged yet!

**Comment by Hjortsberg** [comment]
Good for me that I didn't began fixing this then 😄.
