### ISSUE TITLE
Bug: Cookie or something else is incorrectly set (after a while)

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#165]
It seems like the server or Redis store get stuck in some weird mode after a while so that all cookie attributes (like the username) is empty.

**Comment by Hjortsberg** [comment]
Are we sure this is the case? We don't accidentally empty/reassign it somewhere or reference A new instance or something?

**Comment by willeponken** [comment]
Well it only happens after a while, but I don't know.

**Comment by willeponken** [comment]
Forgot to mention: a restart of the server solves the problem, without any deletion of cookies etc.

**Comment by willeponken** [comment]
This was _probably_ fixed in #177, so I'll close this issue for now. Just re-open this issue if the bug pops up again.
