### ISSUE TITLE
Reset deploy database and restart 

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#168]
Hello, I cannot find the friend button, I assume this is because the database hasn't been updated for the new changes?

**Comment by Hjortsberg** [comment]
Uuhh, IF I'm not mistaken, the friend button should appear anyhow. This doesn't sound to good.

**Comment by Hjortsberg** [comment]
What on earth. There is some really wierd version on the live server. My error messages are not there either. And they where implemented before your feed.

**Comment by willeponken** [comment]
Maybe the deployment failed due to the differences with the DB?

Den tor 27 dec. 2018 21:08Philip Hjortsberg <notifications@github.com>
skrev:

**Comment by Hjortsberg** [comment]
fixed in: #169
