### ISSUE TITLE
Set up REDIS in AWS

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#17]

**Comment by willeponken** [comment]
Eh, so we need to add the Elasticache Redis instance to the same VPC as the EC2, and then... Profit?

**Comment by willeponken** [comment]
I WILL PUT THIS __ON HOLD__ BECAUSE I CAN, OKAY?!?!?!!!!

So... We will just use a in-memory session store in the mean time - because we only host one EC2 instance and we got no scaling. But! We should fix this l80r!
