### ISSUE TITLE
Server spits out empty error msg on duplicate username on registration.

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#170]
This behaviour is not shown locally.

**Comment by willeponken** [comment]
Huuuuuuujh, out of date DB?

**Comment by Hjortsberg** [comment]
Nein, this was the case before the deployment also. 
But what the heck. the DB might be misssing some features since long back. Pulled the logs and it seems kinda wierd.

**Comment by Hjortsberg** [comment]
Also, seems to be some wierd shit with the registration page. 
At failed registration it SOMETIMES redirects back to an empty registration page. 🚫

**Comment by willeponken** [comment]
Are you sure you're looking at the right logs? It has several dates mixed
in the same file. Anyhow, the DB could be out of date since earlier?

Den lör 29 dec. 2018 16:09Philip Hjortsberg <notifications@github.com>
skrev:

**Comment by Hjortsberg** [comment]
True, I didn't read the right date but doesn't change that i experienced the bug before the update also.
Will check what the current log says

**Comment by willeponken** [comment]
FIX THIS ASAP

**Comment by Hjortsberg** [comment]
GAH chill man

**Comment by willeponken** [comment]
![](https://zippy.gfycat.com/ShockingKindlyIriomotecat.gif)

**Comment by Hjortsberg** [comment]
ONTOPIC: I narrowed down the BUG, it only gives an empty error message IF the user is present in the DB BUT with different case! You can ry this yourself before i delete the db with pbot and PBOT. pbot will give you empty error and PBOT will give you the correct error message.

**Comment by willeponken** [comment]
Ah, yes, looking at the SQL query for `PutUser` I see that it doesn't check if the user already exists (case-insensitive), but it'll give an error for same case due to duplicate PK.

There should exist some smart way of checking for this in PostgreSQL, but I'm unsure.

**Comment by willeponken** [comment]
In other words, it'll add the user but fail the authentication step?

**Comment by willeponken** [comment]
So there should exist both PBOT and pbot, but only one that can be used for logging in?

**Comment by Hjortsberg** [comment]
no the username_user_idx uinique index constraint thros an error but it's unhandled, thus causing a 500 internal

**Comment by willeponken** [comment]
Ah, I forgot about the constraint, well then it's an easy fix!

**Comment by Hjortsberg** [comment]
![image](https://user-images.githubusercontent.com/17297258/50540039-c204d600-0b8a-11e9-9273-5dc2c0c6f827.png)

**Comment by willeponken** [comment]
![](https://giant.gfycat.com/InfatuatedWarmGrizzlybear.gif)

**Comment by willeponken** [comment]
Just add _dat_ smexy error check and return a HTTP Conflict :heart_eyes:

**Comment by Hjortsberg** [comment]
i just restarted the servers and erased the DB.

**Comment by Hjortsberg** [comment]
![ITSDONE](https://media.giphy.com/media/Mp4hQy51LjY6A/giphy.gif)

**Comment by Hjortsberg** [comment]
The redirect error still seems present but very sporadious. not worth fixing.

**Comment by willeponken** [comment]
CLOSE THIS ISSUE BECAUSE IT'S FIXED IN #173 ?!?!?!!

**Comment by willeponken** [comment]
OH NEVERMIND I JUST SAW THAT YOU HAVEN'T MERGED YET.

**Comment by willeponken** [comment]
OKAY NOW YOU HAVE MERGED, CLOSE?!?!?!!?!?

**Comment by Hjortsberg** [comment]
EHAT THE SHIT. I USED THE FIXES:  TAG?! GARBAGE GITHUB HOOKS

fixed in: #173
