### ISSUE TITLE
little white cross for closing error msg doesn't work. 

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#171]
When register or login causes a error message to show, the small white cross is not connected to anything and therefore does nothing. 

Suggested fix: 
Remove cross alternatively connect it to something.

**Comment by willeponken** [comment]
Remove it!

**Comment by Hjortsberg** [comment]
Kill it!

**Comment by Hjortsberg** [comment]
With fire!

**Comment by Hjortsberg** [comment]
![WITHFIRE](https://media.giphy.com/media/PhJgp6i7seqylTE0XJ/giphy.gif)

**Comment by willeponken** [comment]
This is simply removing the `ξ('i.close.icon')` @Hjortsberg

**Comment by willeponken** [comment]
Is this one one?

**Comment by Hjortsberg** [comment]
this is fixed in some commit i don't remember !
