### ISSUE TITLE
Set Up S3 bucket in AWS

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#18]
In order for a CDN to have a purpose, we must serve some form of media to serve. 
Are we going to serve some form of data that will benefit from a CDN @willeponken ?

**Comment by willeponken** [comment]
You're right, there's no reason for a CDN right now, especially during
development.

Den tor 8 nov. 2018 20:31Philip Hjortsberg <notifications@github.com> skrev:

**Comment by willeponken** [comment]
Closing this issue, feel free to re-open if this issue becomes relevant.
