### ISSUE TITLE
show number of followers and following

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#183]
Suggestion and small improvement, in order to make the profile a bit more interesting one could show "followers" and/or"follows". 

The "follows" can be very easy to implement, just get the length of the friends array in frontend.

The "followers" will need a SQL query, backend and API call. 

And of course modify profile and user in frontend.

**Comment by willeponken** [comment]
Would this also list all their friends and friendees? That would be nice.

**Comment by Hjortsberg** [comment]
Could do! This was just something that got to me, of course we could show a complete friend list!

**Comment by willeponken** [comment]
I'd say yes to this!

**Comment by willeponken** [comment]
Move from `On hold` and start implementing?

**Comment by willeponken** [comment]
Hmm, is this one done?

**Comment by Hjortsberg** [comment]
Ah well I see that the issue originally wanted number of. I have not implemented the number part but otherwise yes, this is done.
