### ISSUE TITLE
search not properly redirecting when in a user profile

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#202]
search will not redirect properly if:
1. search for a user.
2. stay at users profile and search for new user.

**Comment by willeponken** [comment]
Hmm, this is probably (just guessing) because we need to update the attrs
using onupdate.

Den sön 6 jan. 2019 02:19Philip Hjortsberg <notifications@github.com> skrev:

**Comment by Hjortsberg** [comment]
I might have lied a little here. Hehe.
The URL updates just fine if I recall correctly, just doesn't redraw.
