### ISSUE TITLE
Design front end architecture

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#22]
We've already chosen React as our frontend framework.

**Comment by willeponken** [comment]
We'll use D3 for generating graphs/charts.

**Comment by willeponken** [comment]
TypeScript will be used instead of JavaScript.

**Comment by willeponken** [comment]
Redux for state?

**Comment by willeponken** [comment]
Jest and Enzyme for testing?

**Comment by willeponken** [comment]
Ja men va\*\*n, nu bestämmer jag att vi kör på (ja but what the h\*\*l nu I decide we go för):
 * React
 * Redux
 * D3
 * TypeScript
 * Jest and Enzyme

:microphone: :wave:

**Comment by Hjortsberg** [comment]
Done and done!
