### ISSUE TITLE
refactor: remove bloat and bootstrap Mithril + TypeScript 

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#35]
Hello gents, we'll change from the __bloated__ stack:
 * React
 * Redux
 * D3
 * TypeScript

And switch to, *the __far superior__*:
 * ~~BloatboneJS~~ :-1: 
 * TypeScript
 * D3
 * Mithril

### EPIC.

This ticket includes:
 * Bootstraping with npm, webpack, TypeScript
 * Add an example model + view + controller
 * Update the .travis.yml, if necessary (?)

### GO!

**Comment by willeponken** [comment]
@Hjortsberg removed the *__heavily__* bloated BackboneJS (due to your discovery of the jQuery bloatware). jQuery is de-facto required because of DOM manipulation and stuff.

**Comment by willeponken** [comment]
I feel betrayed by BackboneJS. :sob:

**Comment by willeponken** [comment]
Hmm, the numbers doesn't add up...
![2018-11-13-155003_621x128_scrot](https://user-images.githubusercontent.com/4541181/48420965-d8321080-e75b-11e8-9915-dd3e48d0c651.png)

But meh, 20-44 KB still sucks.

**Comment by Hjortsberg** [comment]
Horrible, I thought Backbone.js was going to be our savior in the search for the perfect .js framework.

**Comment by willeponken** [comment]
BackboneJS has just been added to my sucky-framework-list.

**Comment by willeponken** [comment]
Maybe add this as some kind of boilerplate: https://mithril.js.org/simple-application.html

**Comment by willeponken** [comment]
We need the type definitions too, apparently: https://github.com/MithrilJS/mithril.d.ts

**Comment by willeponken** [comment]
https://www.typescriptlang.org/docs/handbook/classes.html
