### ISSUE TITLE
User authentication using Facebook and/or Google

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#56]
In order to increase ease of registration and sign in and therefore reach a bigger user base we could implement Facebook and Google authentication / sign up.

The solution would use the API's for the services mentioned above.

**Comment by willeponken** [comment]
Hmm, and maybe GitHub OAuth too? I'd say we should put this on hold, but keep it open until later.

**Comment by willeponken** [comment]
CLOSE BECAUSE WE RESPECT OUR USERS PRIVACY?!

**Comment by willeponken** [comment]
BYE
