### ISSUE TITLE
Collaborator/developer guide

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#57]
### HELLO FELLOW HUMANS!

We need a collaborator/developer guide for developing with our project. 

#### Some stuff that should be explained:
   - Installing dependencies.
   - Explain where to look for documentations (such that each directory contains a README.md).
   - Workflow for both frontend and backend.
   - Setting up databases (development specific, not for AWS deployment)
     * PostgreSQL (using Docker, like:
```docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres```)
     * Redis (probably also using Docker?)

_And so on..._

#### Any more suggestions?

**Comment by Hjortsberg** [comment]
I can tackle this issue by doing exhaustive guides, visualizations or video tutorials. Or a combination of previously mentioned techniques.

**Comment by willeponken** [comment]
At the moment I'm just thinking about adding what steps are required as we continue our development, like:

Clone repository:
```
git clone ...
```

Setup frontend dependencies:
```
pushd www && npm install ; popd
```

Start backend server:
```
go run github.com/LuleaUniversityOfTechnology/2018-project-roaster/cmd/roasterd
```

Start frontend autobuild:
```
pushd www && npm start ; popd
```

View web page at:
```
http://localhost:5000
```

Etc.

**Comment by willeponken** [comment]
In the end, before release, we should probably do something with visualizations as you say.
