### ISSUE TITLE
Client-side validation for authentication and connect with REST API

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#60]
Implement client-side validation for login form. Add logout button. Connect everything with the REST API.

Blocked by #59

**Comment by willeponken** [comment]
Issue #59 partially block the REST part. Validation should be handled both on the backend and frontend. You could begin with the frontend validation while I work on my PR: #71.

So what should be done, and in what order?
1. Add client side validation (minimum password length, e-mail validation etc.).
   - Look into the zxcvbn password validation library (it's old, maybe there's something better now?)
   - Make it beautiful!
2. Begin implementation of sending a `m.request` with login registration data.
3. Couple with the REST API (backend).
4. ???
5. PROFIT!

**Comment by willeponken** [comment]
Uhhmmm. We've only implemented the register form, the login form is missing! Don't forget that is part of this ticket :)

**Comment by Hjortsberg** [comment]
True! I've not wireframed that but my plan is to have a simple link or text box on the sign in /register page for the opposite. I think sign in should be default and the button should change to register. Sounds good?

**Comment by willeponken** [comment]
Sound good!
