### ISSUE TITLE
Pre-study: Text input / editor for code

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#61]
Look around the interwebs for a simple and minimal editor for code that can be implemented in the front end. Either some kind of library or maybe do it from scratch.

**Comment by Hjortsberg** [comment]
Some discussion material:

https://github.com/adamjimenez/shiftedit
https://github.com/xwiki-labs/cryptpad
https://github.com/ajaxorg/ace (https://ace.c9.io/ )

**Comment by willeponken** [comment]
Nice! :smile:

**Comment by Hjortsberg** [comment]
Prestudy concluded: Microsoft Monaco editor is the chosen one!
https://github.com/Microsoft/monaco-editor
