### ISSUE TITLE
Add initial stylesheet that reflects the wireframes in doc/wireframes

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#63]

**Comment by Hjortsberg** [comment]
Where in the file structure do we want the .css ?

**Comment by willeponken** [comment]
I'd say: www/styles/*.css


Den sön 18 nov. 2018 22:03Philip Hjortsberg <notifications@github.com>
skrev:

**Comment by willeponken** [comment]
Or we use Sass, SCSS or Less ;)

**Comment by Hjortsberg** [comment]
Of course, feels like the difference between SCSS and sass is very subtle. Feels like we could go for either one, but SCSS seems nice at a first glance. Let's discuss this tomorrow!

**Comment by willeponken** [comment]
Indeed!

Den sön 18 nov. 2018 22:30Philip Hjortsberg <notifications@github.com>
skrev:

**Comment by Hjortsberg** [comment]
Side note, Mithril them selves mention that https://github.com/dwyl/learn-tachyons fit well with the mithril framework. Might be something to look into!

**Comment by Hjortsberg** [comment]
As per discussion, we use Semantic UI for most part. When needed we override with bss (better style sheets).

**Comment by willeponken** [comment]
Wow! Nice!

**Comment by Hjortsberg** [comment]
*insert random positive comment from william bot here*

**Comment by willeponken** [comment]
Agree, thanks!
