### ISSUE TITLE
Pick password hash algorithm(s)

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#64]
Pick between these three __real__ password hash-algorithms: bcrypt, scrypt or PBKDF2 (I'm aware of Argon2 but it's way to young). 

PBKDF2 is easier to bruteforce using FPGA's. Scrypt is made to be tough to implement on FPGA's and hardware, but is younger than bcrypt. I feel bcrypt is the middle ground that is both mature and is hard _enough_ to bruteforce. Bcrypt has a limit of 72 bytes long input - meaning it'll truncate the password after 72 bytes :scream: (not that big of a deal).

I'm voting for bcrypt, but...

Just to be crazy and stuff, I also vote for pre-hashing the password with SHA-512 (64 bytes), so the input after 72 bytes also is used (entropy after 72 bytes still has meaning, yay!).

```go
passwordHash = bcrypt(sha512(password))
```

Note: Make sure the Go implementation of bcrypt doesn't end reading at the `0x00` character, because SHA-512 may output that.

**Comment by Hjortsberg** [comment]
Interesting article, I vote for brypt since both dropbox and you have faith in it.

**Comment by willeponken** [comment]
Great! Then it's decided!
