### ISSUE TITLE
Choose in-memory data store (MEMCACHED / REDIS)

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#7]
Read up on REDIS vs MEMCACHED, choose one.

**Comment by Hjortsberg** [comment]
Considering the below post, I think that it is clear that we should use REDIS.
https://stackoverflow.com/questions/10558465/memcached-vs-redis
Your opinion is wanted though @willeponken.

**Comment by willeponken** [comment]
Yes, I agree! Let's go with Redis 😎

Den tor 8 nov. 2018 19:32Philip Hjortsberg <notifications@github.com> skrev:

**Comment by willeponken** [comment]
We have decided for Redis, closing.
