### ISSUE TITLE
Redirect to TLS version of website

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#70]
**Describe the bug**
The regular **http**:// doesn't redirect to the TLS encrypted **https**://.

**To Reproduce**
1. Enable incognito mode
2. Go to '**http**://roast.software'
3. No redirect to '**https**://roast.software'

**Expected behavior**
A redirect to '**https**://roast.software'.

**Screenshots**
![2018-11-20-104358_794x133_scrot](https://user-images.githubusercontent.com/4541181/48764885-335e8880-ecb1-11e8-9049-4779adfe63aa.png)

**Desktop (please complete the following information):**
 - OS: Linux voltaire 4.14.65-gentoo GNU/Linux
 - Browser: Mozilla Firefox
 - Version: 60.3.0

**Additional context**

**Comment by Hjortsberg** [comment]
See: https://aws.amazon.com/premiumsupport/knowledge-center/redirect-http-https-elb/

> If you're using Classic Load Balancers, you can’t redirect HTTP traffic to HTTPS at the load balancer level. Instead, implement any redirection logic in the web servers behind the load balancers.

**Comment by willeponken** [comment]
Ah! Well then, I'll add this to the backend.
