### ISSUE TITLE
AWS EB auto-deploy timeout since commit 77a74da

### ISSUE THREAD

**Issue by willeponken** [LuleaUniversityOfTechnology/2018-project-roaster#74]
Since commit 77a74da the webpack compilation takes longer than 10 minutes(!!!).

We shouldn't bundle in Monaco IDE and its assets in our app bundle.

Instead, we should lazy-load the Monaco IDE (adding a nice spinner while downloading).

**Comment by willeponken** [comment]
The Monaco webpack plugin also allows for selecting specific features: https://github.com/Microsoft/monaco-editor-webpack-plugin

**Comment by willeponken** [comment]
I'm on this now.

**Comment by Hjortsberg** [comment]
Nice, I believe that we should only load the necessary features and modules (languages and editor features). Gogogo!

**Comment by willeponken** [comment]
Omg Babel has a inbuilt typescript loader

**Comment by willeponken** [comment]
Uhmm, so I will keep this open a little until the CI builds are fixed.
