### ISSUE TITLE
Fix a valid deployment again, AWS

### ISSUE THREAD

**Issue by Hjortsberg** [LuleaUniversityOfTechnology/2018-project-roaster#78]
Due to our deployment strategy having a small flaw, the latest build of our application was not properly deployed to AWS! 

This must be fixed before tomorrow when we are supposed to present.

I assign you @willeponken , since you are the man with the plan when it comes to our deployment.

**Comment by willeponken** [comment]
:sob:

**Comment by willeponken** [comment]
Do not forget that it's the frontend that is so bloated that it takes longer than 60 minutes to run the `npm build`.
